// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiyEV80KtskypEXOmAnb3F_IC5jPKc0Y0',
    appId: '1:1097044033753:web:05c4ae97ff2c67f6037ec8',
    messagingSenderId: '1097044033753',
    projectId: 'newmobileproject-c7f26',
    authDomain: 'newmobileproject-c7f26.firebaseapp.com',
    storageBucket: 'newmobileproject-c7f26.appspot.com',
    measurementId: 'G-6XVDJT7ZXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAibwF650Gzz-o7EjyyPcpxv48UyloP9Js',
    appId: '1:1097044033753:android:d0e8eb48ed331dd7037ec8',
    messagingSenderId: '1097044033753',
    projectId: 'newmobileproject-c7f26',
    storageBucket: 'newmobileproject-c7f26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZOiUpo41azQgR3UZmJgfyUK3z1aBwJGw',
    appId: '1:1097044033753:ios:f976a6c3c12a02ae037ec8',
    messagingSenderId: '1097044033753',
    projectId: 'newmobileproject-c7f26',
    storageBucket: 'newmobileproject-c7f26.appspot.com',
    iosClientId: '1097044033753-0jnqh6b82nktp6pghm17iibii73pk7qb.apps.googleusercontent.com',
    iosBundleId: 'com.berke.helvaci',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZOiUpo41azQgR3UZmJgfyUK3z1aBwJGw',
    appId: '1:1097044033753:ios:f976a6c3c12a02ae037ec8',
    messagingSenderId: '1097044033753',
    projectId: 'newmobileproject-c7f26',
    storageBucket: 'newmobileproject-c7f26.appspot.com',
    iosClientId: '1097044033753-0jnqh6b82nktp6pghm17iibii73pk7qb.apps.googleusercontent.com',
    iosBundleId: 'com.berke.helvaci',
  );
}
